### ISSUE TITLE
I can't use it with php 5.5

### ISSUE THREAD

**Issue by Jimmi08** [arunshekher/mentions#12]
Hi, I got error with php 5.5.11 (localhost)

Parse error: syntax error, unexpected '.', expecting ']' in   \mentions\admin_config.php on line 74

With php 5.5.11 is not posible to combine strings in e107 prefs.  (I noticed this somewhere)

But I have older installation with php 5.6 and e107 2.1.6 and it works.

**Comment by arunshekher** [comment]
Hi @Jimmi08, Thank you for reporting. 👍, it's seems that it's because property initialization of a class must not depend on runtime values. (http://php.net/manual/en/language.oop5.properties.php) I never tested it below PHP 5.6 as 5.6 itself is nearing the end of its security support period. Will try to rectify the issue with next release. Thanks again.

**Comment by Jimmi08** [comment]
Hi, thank you for looking into this. I was able to fix this by adding new lang strings (and combine strings in language file). Normally I use php 7, but on home local notebook I am not able update my xampp version. I can't lost other projects I have there.  Now I have my own installation for my community sites and I wanted to have this plugin as part of core. 

At first, I found how to fix this problem (to move it to __construct method), but then admin_ui started to have problems. It said that there is no object fo AddTitle or so and really getResponse() was empty (no object).  Maybe there is some problem in core itself?   

Thank you

**Comment by arunshekher** [comment]
Thank you for the pointers I'll look into to your suggestions when I'm at it. And thank you for considering to give this plugin a whirl in your community sites. 

I haven't tinkered much with admin_ui class so can't comment anything useful about it. 😄

**Comment by Jimmi08** [comment]
Me  neither. But you are able to confirm that your code is correct and then create issue on core repo

**Comment by arunshekher** [comment]
I'm bit anxious when it comes to communication especially where language barriers exists. Some times genuine concerns can be taken as complaining.

**Comment by Jimmi08** [comment]
I know exactly what you mean. But after time I became resistent and its their problem. I am just trying help.  You could create branch and fix admin_config for php 5.5.  If I am sure that file is correct, I can create issue myself. I just dont know OOP enough to be sure its not my mistake.

**Comment by arunshekher** [comment]
@Jimmi08, In this particular case it's my mistake. Below PHP 5.6 we're not supposed to do any operation (concatenation is one) as part of initialization in a class. 

I was saying in general I tend to be reluctant to post issues at the core repo unless I'm absolutely sure about it. I'll be adding a bug fix branch as soon as I get some time for it.
