### ISSUE TITLE
question why is parsing used in admin area too

### ISSUE THREAD

**Issue by Jimmi08** [arunshekher/mentions#13]
I noticed this in debug mode:
Isn't it useless to executing this in admin area?
 
![image](https://user-images.githubusercontent.com/5429548/41975247-77ac042c-7a1a-11e8-8d59-3bbeb1bae738.png)

**Comment by arunshekher** [comment]
@Jimmi08, Indeed it's absolutely useless, I had just left it at the default e_parse addon behavior. As a cumulative improvement, with the next upgrade I'll try to incorporate a method to check for user-area (avoid admin-area ) before the parser is called. Thank you for the suggestion.
