### ISSUE TITLE
chatbox - date/time is not inserted in email

### ISSUE THREAD

**Issue by Jimmi08** [arunshekher/mentions#9]
This is empty:

			`$this->mentionDate = $this->getMentionDate($data['datestamp']);`

if I print_a(); $data inside chatbox() method, there is not datestamp field

![image](https://user-images.githubusercontent.com/5429548/30368313-1a854348-9871-11e7-8d25-10d200650f96.png)

**Comment by arunshekher** [comment]
@Jimmi08,
$data['datestamp'] will only be available if [this commit at e107 repo](https://github.com/e107inc/e107/commit/6578870398b4d06a59a0b74140eb15951343f55d) is applied to your e107 installation.

**Comment by Jimmi08** [comment]
Fixed by update. Thank you

**Comment by arunshekher** [comment]
👍
